location="eastus"
rg-name="tf-resources-prod-rg"
storage-account-name="proddemowebsite"
index_document="index.html"
source_content="<h1>This is static content coming from the Production Terraform</h1>"
environment="prod"