trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: terraform_build
  jobs:
  - job: build
    steps:
    - task: CopyFiles@2
      inputs:
          SourceFolder: 'terraform'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Artifacts'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: tfBuildFiles

- stage: terraform_dev
  dependsOn: terraform_build
  displayName: "Terraform dev deploy"
  variables:
  - template: ./vars/dev-vars.yml
  jobs:
  - template: templates/terraform-temps.yml
    parameters:
      serviceConnection: 'tf-dev-sc'

# Set Manual approvals
- stage: terraform_prod
  displayName: "Terraform prod deploy"
  variables:
  - template: ./vars/prod-vars.yml
  jobs:
  - template: templates/terraform-temps.yml
    parameters:
      serviceConnection: 'tf-prod-sc'